name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          cache: npm

      - name: Enter Directory
        run: cd docs

      - name: Install
        run: npm install

      - name: Build
        run: npx vuepress build .

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages-code
          build_dir: .vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_TOKEN }}
